Public class FMG_StaticConstant {
    public static final string BrainTreeMetadataName = 'Brain_Tree_payment_details';
    public static final string FailedMessage = 'Payment Failed';
     public static final string SuccessMessage = 'Success';//InteractionType
    public static final string GATEWAY_REJECTED = 'GATEWAY_REJECTED';
     public static final string GatewayMessage = 'transaction is completed successfully';
    public static final string InteractionType = 'Capture';
     public static final string InteractionType1 = 'Authorization';

}